# Generated by Django 2.2.5 on 2019-09-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'POSITIVE'), ('negative', 'NEGATIVE')], default='negative', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacker_news_id', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField()),
                ('up_vote', models.IntegerField()),
                ('sentiment', models.ManyToManyField(related_name='sentiment_field', to='articles.Sentiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticlesUser')),
            ],
        ),
    ]
